import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
padding = {x = 5, y = 5}

[env]
TERM = "xterm-256color"


[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
