import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
padding = {x = 5, y = 5}
# opacity = 0.8

[env]
TERM = "xterm-256color"


[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
