#!/bin/bash

AC_POWER=$(cat /sys/class/power_supply/AC0/online)
CACHE_FILE="$HOME/.cache/hypr-power-mode"

if [ "$AC_POWER" -eq 1 ]; then
  CURRENT_MODE="AC"
  ICON=""
else
  CURRENT_MODE="Battery"
  ICON=""
fi

LAST_MODE=""
if [ -f "$CACHE_FILE" ]; then
  LAST_MODE=$(cat "$CACHE_FILE")
fi

if [ "$CURRENT_MODE" != "$LAST_MODE" ]; then
  if [ "$CURRENT_MODE" == "AC" ]; then
    sed -i 's/^monitor=.*/monitor=,1920x1200@144,auto,1.0/' ~/.config/hypr/hyprland.conf
    sed -i 's/^    enabled = no # Animations Tag/    enabled = yes # Animations Tag/' ~/.config/hypr/hyprland.conf
    sed -i 's/^    inactive_opacity = 1.0 # Window Opacity/    inactive_opacity = 0.95 # Window Opacity/' ~/.config/hypr/hyprland.conf
  else
    sed -i 's/^monitor=.*/monitor=,1920x1200@60,auto,1.0/' ~/.config/hypr/hyprland.conf
    sed -i 's/^    enabled = yes # Animations Tag/    enabled = no # Animations Tag/' ~/.config/hypr/hyprland.conf
    sed -i 's/^    inactive_opacity = 0.95 # Window Opacity/    inactive_opacity = 1.0 # Window Opacity/' ~/.config/hypr/hyprland.conf
  fi

  hyprctl reload > /dev/null
  echo "$CURRENT_MODE" > "$CACHE_FILE"
fi

echo "$ICON"

