# The basic colors
foreground              #cdcdcd
background              #141415
selection_foreground    #141415
selection_background    #405065

# Cursor colors
cursor                  #cdcdcd
cursor_text_color       #141415

# URL underline color when hovering with mouse
url_color               #6e94b2

# Kitty window border colors
active_border_color     #878787
inactive_border_color   #252530
bell_border_color       #f3be7c

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #141415
active_tab_background   #c3c3d5
inactive_tab_foreground #606079
inactive_tab_background #141415
tab_bar_background      #141415

# Colors for marks (marked text in the terminal)
mark1_foreground #141415
mark1_background #e8b589
mark2_foreground #141415
mark2_background #e0a363
mark3_foreground #141415
mark3_background #c48282

# The 16 terminal colors

# black
color0 #141415
color8 #252530

# red
color1 #df6882
color9 #df6882

# green
color2  #8cb66d
color10 #8cb66d

# yellow
color3  #f3be7c
color11 #f3be7c

# blue
color4  #7e98e8
color12 #7e98e8

# magenta
color5  #bb9dbd
color13 #bb9dbd

# cyan
color6  #90a0b5
color14 #90a0b5

# white
color7  #cdcdcd
color15 #cdcdcd
